-- DDL 관리를 이런 식으로 해주는 것이 좋다.
drop table if exists member CASCADE;
    create table member
    (
        id   bigint generated by default as identity,
        name varchar(255),
        primary key (id)
);

